# -*- coding: utf-8 -*-
"""bridge_yolov5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MDaxCHcjjZYO4KJjO5QypH9EOZ8FzfjQ

# Setup

Connect to google drive
"""

from google.colab import drive
drive.mount('/content/drive')

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/drive/MyDrive/yolov5-code/yolov5-master

"""# Installing requirements"""

# Commented out IPython magic to ensure Python compatibility.
# %pip install -qr requirements.txt  # install

import torch
import utils
display = utils.notebook_init()  # checks

"""# Training The Dataset"""

!python train.py --img 640 --batch 16 --epochs 150  --data bridge.yaml --weights yolov5s.pt --cache

"""# Detection"""

!python detect.py --weights runs/train/exp17/weights/best.pt --img 640 --conf 0.25 --source /content/drive/MyDrive/test-images/2.jpg

"""# Validation"""

# Validate YOLOv5s on COCO val
!python val.py --weights runs/train/exp17/weights/best.pt --data bridge.yaml --img 640 --half